name: Tests
on:
  push:
    branches:
      - master
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
